eureka:
  client:
    serviceUrl:
      defaultZone: http://micro-eureka:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: micro-zuul
zuul:
  routes:
    api-a:
      path: /api-ribbon/**
      serviceId: micro-ribbon
    api-b:
      path: /api-feign/**
      serviceId: micro-feign